### ISSUE TITLE
NPM install errors

### ISSUE THREAD

**Issue by HansHauge** [mapbox/mapbox-directions.js#107]
For the same reason that the [build is broken](https://travis-ci.org/mapbox/mapbox-directions.js/builds/145940523) we have had to remove `mapbox-directions.js` from our code base.

Although it is possible to build locally, we cannot deploy to Jenkins with the errors produced.

``` Bash
  npm install mapbox-directions.js
> contextify@0.1.15 install /Users/hhauge/development/foo/node_modules/contextify
> node-gyp rebuild
```

**Comment by tmcw** [comment]
Can you provide the full error? It's not clear that your build breakage has the same cause as the travis breakage, or what it is.

**Comment by tadjohnston** [comment]
I would like to look into this a little more.  Locally this works fine, but with our Jenkins server this fails completely on this package.  It took a while to find the issue and our other repos use the same Jenkins configurations and such, so it's possible that it's an issue on our end somewhere.

**Comment by iredmedia** [comment]
I'm getting an error, not sure if this is related?

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kevinredman/Code/bookseats/public/vendors/mapbox-directions.js/node_modules/contextify
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevinredman/Code/bookseats/public/vendors/mapbox-directions.js/npm-debug.log
```
